name: rick_and_morty
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+202304021447

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cached_network_image: ^3.2.1
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_data: ^1.5.6
  flutter_riverpod: ^2.3.2
  freezed_annotation: ^2.0.3
  intl: ^0.17.0
  json_annotation: ^4.8.0
  material_design_icons_flutter: ^5.0.6996
  retrofit: ^3.3.1
  shared_preferences: ^2.0.15
  sizer: ^2.0.15
  connection_notifier: ^1.0.1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.5.0
  retrofit_generator: ^4.2.0

flutter:

  uses-material-design: true
